# Generated by Django 5.1.6 on 2025-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypocluster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
