# Generated by Django 5.1.6 on 2025-03-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_hypocluster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypocluster',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
    ]
