# Generated by Django 5.1.6 on 2025-03-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_hypocluster_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypocluster',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
