# Generated by Django 5.1.6 on 2025-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_alter_hypocluster_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypocluster',
            name='name',
        ),
        migrations.AlterField(
            model_name='hypocluster',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
