# Generated by Django 5.1.6 on 2025-03-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0005_remove_hypocluster_name_alter_hypocluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypocluster',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
