name: HypoLab Backend + Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python for Django
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Django dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Django tests
      run: |
        cd backend
        pytest

    - name: Set up Node.js for React
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install React dependencies
      run: |
        cd frontend
        npm install

    - name: Run React tests
      run: |
        cd frontend
        npm test -- --coverage

    - name: Build React frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy Django backend (Docker example)
      run: |
        cd backend
        docker build -t my-django-backend .
        docker push my-docker-repo/my-django-backend:latest

    - name: Deploy React frontend (example using Netlify)
      run: |
        cd frontend
        npm run build
        netlify deploy --dir=build --prod
