name: HypoLab Backend + Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python for Django
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Django dependencies
      run: |
        pip install -r hypolab/requirements.txt

    - name: Run Django tests
      run: |
        cd hypolab
        pytest

  frontend_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js for React
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Cache npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install React dependencies
      run: |
        cd frontend
    - name: Run React tests
      run: |
        cd frontend
        npm test -- --coverage

    - name: Build React frontend
      run: |
        cd frontend
        npm run build

  deploy_backend:
    runs-on: ubuntu-latest
    needs: backend_build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Django backend (Docker example)
      run: |
        cd backend
        docker build -t my-django-backend .
        docker push my-docker-repo/my-django-backend:latest

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: frontend_build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy React frontend (example using Netlify)
      run: |
        cd frontend
        npm run build
        netlify deploy --dir=build --prod